### ISSUE TITLE
occurrences failing due to no citation.csv

### ISSUE THREAD

**Issue by johnbaums** [AtlasOfLivingAustralia/ALA4R#12]
It seems that citation.csv is no longer included in the archives downloaded by `occurrences`, and so the following (in `occurrences`) triggers an error:

```
xc = read.table(unz(thisfile, "citation.csv"), header = TRUE, 
        comment.char = "", as.is = TRUE)
```

E.g.:

```
occurrences('Acacia kingiana', download_reason_id=10)
## Please use (fixed|coll|regex)(x, ignore_case = TRUE) instead of ignore.case(x)
## Please use (fixed|coll|regex)(x, ignore_case = TRUE) instead of ignore.case(x)
## Error in open.connection(file, "rt") : cannot open the connection
## In addition: Warning messages:
##   1: closing unused connection 7 (C:\Users\John\AppData\Local\Temp\RtmpAtgTb8/54bb20636a2fef42b96ca50024152010:citation.csv) 
## 2: In open.connection(file, "rt") :
##   cannot locate file 'citation.csv' in zip file 'C:\Users\John\AppData\Local\Temp\RtmpAtgTb8/3b7d4c346db6d4687a8f00515ed42c98'
```

**Comment by raymondben** [comment]
Hmmm, odd, I don't get the same error. Can you paste the output of `sessionInfo()` please?

**Comment by johnbaums** [comment]
Seems to be working again - sorry...

**Comment by johnbaums** [comment]
I was also getting some odd errors re ala-rufus.it.csiro.au not responding. I've started a new session and things are working as expected... may be coincidental though because I had a couple of colleagues (here and elsewhere) test it as well. Anyway - all seems ok. :)

**Comment by raymondben** [comment]
I'll blame the ALA servers! But I might wrap the citation.csv-related code in a `try` block anyway, so future failures don't bring the whole show to a halt.
Thanks - B
