### ISSUE TITLE
Filtering `occurrences` by date with `fq`

### ISSUE THREAD

**Issue by johnbaums** [AtlasOfLivingAustralia/ALA4R#13]
`occurrences` does not play nicely with date ranges passed to `occurrence_year` via `fq`, such as:

```
occurrences(taxon='lsid:urn:lsid:biodiversity.org.au:afd.taxon:ba8d0c3b-9753-46cf-87b4-a1b9ec290634',
            fq='occurrence_year[2000-01-01T00:00:00Z TO 2020-01-01T23:59:59Z]',
            record_count_only=TRUE)
## ...
## Error in check_fq(fq, type = "occurrence") : 
## invalid fields in fq: occurrence_year[2000-01-01T00, 2020-01-01T23. See ala_fields("occurrence_indexed")
```

yet http://biocache.ala.org.au/ws/occurrences/search?q=lsid:urn:lsid:biodiversity.org.au:afd.taxon:ba8d0c3b-9753-46cf-87b4-a1b9ec290634&fq=occurrence_year:[2000-01-01T00:00:00Z%20TO%202020-01-01T23:59:59Z]&pageSize=0 returns the expected, date-filtered result.

URL encoding the spaces and/or colons in the `occurrences` call doesn't get around this (returns count=0).

Am I using the wrong incantation here, or might `check_fq` be adjusted to permit this type of date filtering? Skipping over `check_fq` results in a [working url](http://biocache.ala.org.au/ws/occurrences/search?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3Aba8d0c3b-9753-46cf-87b4-a1b9ec290634&fq=occurrence_year%3A%5B2000-01-01T00%3A00%3A00Z%20TO%202020-01-01T23%3A59%3A59Z%5D&pageSize=0&facet=off) being constructed, and the correct count (35693, today at least) being returned.

**Comment by raymondben** [comment]
There's a minor typo in your R command: you need a colon after occurrence_year. Nevertheless, it still doesn't work because `check_fq` doesn't handle ranges. Obviously it needs to have more sophisticated parsing: as a workaround for the time being I've just changed `check_fq` to issue a warning rather than an error (v1.19)

**Comment by raymondben** [comment]
fq parsing is now more robust (v1.191), but probably not foolproof - so I've left it as issuing a warning rather than an error

**Comment by johnbaums** [comment]
Nice one, thanks Ben.
