### ISSUE TITLE
ALA download requests - add sourceTypeId param

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ALA4R#16]
When performing an ALA records download, add an extra request param:

`sourceTypeId=2001`

which corresponds to ALA4R source, as defined at http://logger.ala.org.au/service/logger/sources

**Comment by djtfmartin** [comment]
We should be doing something with user-agents to tracking ALA4R requests. Wondering if this functionality has fallen by the way side.

**Comment by djtfmartin** [comment]
See https://github.com/AtlasOfLivingAustralia/logger-service/blob/master/grails-app/services/au/org/ala/logger/LoggerService.groovy#L30

cc @m-r-c

**Comment by raymondben** [comment]
Done. As of AL4R v1.24, the ```occurrences()``` function includes ```sourceTypeId``` as a query parameter to its web call.
In addition, *all* ALA4R calls to ALA web services use a user-agent string of the form "ALA4R ALA4R_version (R_version_and_platform)" as has always been the case.
