### ISSUE TITLE
Unexpected species match with `search_names`

### ISSUE THREAD

**Issue by johnbaums** [AtlasOfLivingAustralia/ALA4R#19]
Searching for "Melaleuca fluviatilis" returns a match to Melaleuca fluviatilis x M.nervosa, despite Melaleuca fluviatilis [existing in ALA](http://bie.ala.org.au/species/http://id.biodiversity.org.au/node/apni/2915874#overview).

```r
search_names('Melaleuca fluviatilis')
#              searchTerm                              name commonName    rank                                      guid
# 1 Melaleuca fluviatilis Melaleuca fluviatilis x M.nervosa         NA unknown     ALA_Melaleuca_fluviatilis_x_M.nervosa
```

In case it's relevant, my code suggests that in the past, the LSID for this species was urn:lsid:biodiversity.org.au:apni.taxon:251180.

**Comment by raymondben** [comment]
The search mismatch itself is an issue in the underlying service: transferred to https://github.com/AtlasOfLivingAustralia/bie-index/issues/75

As for the LSID, apparently some LSIDs have recently been updated - the LSID for M. fluviatilis now appears to be http://id.biodiversity.org.au/node/apni/2915874

**Comment by raymondben** [comment]
Matching of subspecies or hybrids in preference to species should now be fixed, see https://github.com/AtlasOfLivingAustralia/bie-index/issues/75
