### ISSUE TITLE
Cannot locate citation.csv

### ISSUE THREAD

**Issue by johnbaums** [AtlasOfLivingAustralia/ALA4R#20]
`occurrences` is throwing a warning message about not finding citation.csv. It seems that since the revamp of ALA, citation.csv is no longer included in the download.

e.g.: 

```r
occ <- occurrences('lsid:http://id.biodiversity.org.au/name/apni/245602', 
+                       fq='geospatial_kosher:true', 
+                       download_reason_id=7)$data
Warning message:
In open.connection(file, "rt") :
  cannot locate file 'citation.csv' in zip file 'C:\Users\John\AppData\Local\Temp\RtmpIdSthN/23cf28750657a4b5079f891547c21398'
```

**Comment by raymondben** [comment]
Confirmed - citation.csv no longer appears to be provided. I think it has been replaced by a README.html file. Am awaiting confirmation from ALA devs before updating the ALA4R code.

**Comment by raymondben** [comment]
Still not entirely sure that citation.csv has been officially replaced by README.html, but am just checking for both now and it won't warn about not finding citation.csv if it finds the README (v1.27).
