### ISSUE TITLE
geodeticDatumOriginal instead of geodeticDatum?

### ISSUE THREAD

**Issue by johnbaums** [AtlasOfLivingAustralia/ALA4R#22]
For a record such as [this](http://biocache.ala.org.au/occurrences/b9022246-de53-43a2-952d-5f85bd9948c0), where supplied geodetic datum is not WGS84, `occurrences` returns the supplied datum (epsg:4202 for the record above) in the `geodeticDatum` element. 

Would this be better returned as `geodeticDatumOriginal`, with the processed datum given in `geodeticDatum` instead (since the coordinates given in `latitude` and `longitude` seem to correspond to WGS84)?

**Comment by raymondben** [comment]
Looks like an issue with the underlying service: transferred to https://github.com/AtlasOfLivingAustralia/biocache-service/issues/124

**Comment by raymondben** [comment]
See Dave's comment on https://github.com/AtlasOfLivingAustralia/biocache-service/issues/124
