### ISSUE TITLE
specieslist() returns error when fq is only parameter specified

### ISSUE THREAD

**Issue by snubian** [AtlasOfLivingAustralia/ALA4R#25]
E.g.:
```
> x <- ALA4R::specieslist(fq = c("kingdom:Plantae", "state:New South Wales"))
Error in ALA4R::specieslist(fq = c("kingdom:Plantae", "state:New South Wales")) : 
  invalid request: need either fq or wkt parameter to be specified
```
It works fine if I add a `wkt` parameter.

**Comment by raymondben** [comment]
Hmm, couple of things going on with this one. First, the error message is misleading (i.e. wrong). It should say "need either taxon or wkt parameter to be specified" not "need either fq or wkt parameter to be specified". Easy fix.
But something else has changed with the way the ALA servers deliver this service. The `taxon` parameter doesn't work at all (I think this is an error at the server end), and furthermore a `wkt` query on its own does now work (previously it didn't; I assume this is an undocumented change in behaviour). Shall investigate further ...

**Comment by snubian** [comment]
Thank you for such a quick reply, much appreciated.

The `taxon` parameter is working OK for me now:
```
> x <- ALA4R::specieslist(taxon = "Gingidia", fq = c("kingdom:Plantae", "state:New South Wales"))
> x$speciesName
[1] "Gingidia algens"    "Gingidia harveyana" "Gingidia montana"   "Gingidia rupicola"  "Gingidia"  
```

**Comment by raymondben** [comment]
OK, this one should be resolved in the current github version (install with `devtools::github_install("AtlasOfLivingAustralia/ALA4R")` )

```
> x <- ALA4R::specieslist(fq = c("kingdom:Plantae", "state:New South Wales"))
> dim(x)
[1] 16552    12
```

I don't think `taxon` searching works reliably, but this is a back-end server bug that should be resolved on the next indexing run (see https://github.com/AtlasOfLivingAustralia/ALA4R/issues/24#issuecomment-290237018).
