### ISSUE TITLE
How to allow spaces in fq parameter

### ISSUE THREAD

**Issue by snubian** [AtlasOfLivingAustralia/ALA4R#28]
There seems to be a recent change such that the following now returns zero records (was working fine several months back):

```
x <- ALA4R::specieslist(taxon = "Acacia", fq = c("state:New South Wales"))
```
If I change `New South Wales` to `Queensland` all is well:
```
x <- ALA4R::specieslist(taxon = "Acacia", fq = c("state:Queensland"))
```
I tried changing the spaces to obvious things such as `+` or `%20` without luck. Any advice would be greatly appreciated! :)

**Comment by raymondben** [comment]
Use quotes:
```
x <- specieslist(taxon = "Acacia", fq = c("state:\"New South Wales\""))
```
(Needs \" not just ", because they are within quotes themselves). This gives me 412 results - does that seem right?

**Comment by snubian** [comment]
Magic, thanks! I did try single quotes but not the escaped double-quotes. Works perfectly for me now.

Cheers!
