### ISSUE TITLE
Unit tests skipped or failed

### ISSUE THREAD

**Issue by PeggyNewman** [AtlasOfLivingAustralia/ALA4R#32]
Warnings and errors in TestThat output need to be investigated. Problems may be caused by infrastructure changes or data changes. Output attached. Of interest seems to be:

test-lists.R#23
test-occurrences.R#82
test-occurrences.R#83
test-occurrences.R#84
test-occurrences.R#101
test-search-guids.R#21
[test_output.txt](https://github.com/AtlasOfLivingAustralia/ALA4R/files/1892697/test_output.txt)

**Comment by raymondben** [comment]
These all fixed as of https://github.com/AtlasOfLivingAustralia/ALA4R/commit/04e1e45f9e0149c63fee0ff951fa2a4ba06e664b
