### ISSUE TITLE
Make sure CI account/badges point to ALA organisation

### ISSUE THREAD

**Issue by raymondben** [AtlasOfLivingAustralia/ALA4R#38]
appveyor badge points to raymondben account, not AtlasOfLivingAustralia account, should be changed

**Comment by raymondben** [comment]
Time - half a day

**Comment by raymondben** [comment]
I am not sure why the current appveyor setup works by individual user not organization. Does an appveyor team need to be set upt? https://www.appveyor.com/docs/team-setup/

**Comment by peggynewman** [comment]
I set up an ALA team but the appveyor setup works through authorisation through somebody's github repo. So I've just changed it to mine after a fruitless search for a team/org link.
