### ISSUE TITLE
Typo in assertion names

### ISSUE THREAD

**Issue by johnbaums** [AtlasOfLivingAustralia/ALA4R#9]
Typo in `Conversion` (missing its _s_):

```
> grep('Converion', ala_fields('assertions')$name, value=TRUE)
[1] "decimalLatLongConverionFailed"
```

**Comment by raymondben** [comment]
This lies with the underlying service. Issue transferred to https://github.com/AtlasOfLivingAustralia/biocache-service/issues/45
